### ISSUE TITLE
Custom environment and discrete actions

### ISSUE THREAD

**Issue by ConstantinosM** [google-research/planet#38]
Hello!

First of all, excellent work! I am reading the issues (closed and open) and am trying to understand how I can run PLAnet in a custom environment. I am not sure what information I should include in the `tasks.py` file. Could you elaborate a bit more on how I can make it run in a gym compatible environment?

Also, my environment has discrete actions - but I can possibly use continuous actions in the future. I see in the issues that people are trying to map discrete actions to a range of continuous values in order to do the mapping. I would like to ask you, from your perspective, in order to use PLAnet properly with discrete actions shouldnt the math change? (e.g. instead of Gaussians we have multinomials and relevant discrete distributions).

Thanks in advance!

**Comment by danijar** [comment]
Thanks for reaching out. A good way to handle discrete actions would be to plan using categorical instead of normal distributions. The result of the planner would then be the mode, which is a one hot action.

For now, I think the easiest is to wrap the environment to accept a continuous one-hot action rather than an action index. This way, you don't have to change anything in the in-graph simulation loop.

The environments usually return tuple observations. Some or all of the keys can be provided to `task.state_components` for the code to add diagnostic predictors for them (eg for TB summaries). The keys should always include "image" and "reward". There are env wrappers that can automatically call `env.render()` and add an "image" key from that, etc.

Do you have any other questions about how to add a task?

**Comment by ConstantinosM** [comment]
Thank you Danijar for your answer. I have managed to create a wrapper for the discrete environment I use and then I use the gym_env wrapper that you have in the tasks.py file. I am not sure though if I need to use the Async wrapper (better performance?). I found out that there was a class ExternalProcess that is similar to the Async class and was used in the past. In terms of performance what is the best configuration?

**Comment by piojanu** [comment]
Hi @ConstantinosM!

Here you can find a working example of PlaNet for Atari discrete environments (or OpenAI Gym in general):

https://github.com/piojanu/planet/blob/cf52f2f60eae9429e3ed52128ac4c0830014de98/planet/scripts/tasks.py#L150-L172

Here you'll find all the wrappers:
https://github.com/piojanu/planet/blob/master/planet/control/wrappers.py

Hope that helps ;)

**Comment by ConstantinosM** [comment]
Hi @piojanu !

Actually I used your nice Sokoban wrapper to my discrete environment and worked like a charm. I see that you have already a discrete action wrapper in the shared links. Thank you, that's very helpful! I will adapt my code accordingly.


By the way I saw that at your initial Sokoban wrapper you were using ExternalProcess wrapper which seems similar to the Async wrapper in danijar's code. Can either you or danijar shed some light on this wrapper? What's the best configuration to use in a powerful machine?

Thanks a lot again!

**Comment by piojanu** [comment]
Back then we came to the conclusion that it was redundant I think. This ExternalProcess wrapper is used to separate each environment into its own process, so multiple environments (in batched environment) can be played in parallel.
I didn't see Async wrapper in the code though, but something could change in the meantime. To my knowledge it works fine by default and you don't need to add any Async wrappers.

**Comment by danijar** [comment]
Yeah they are the same class, we just renamed it since it now supports both running the environment in a separate thread or process. It can be useful to avoid rendering issues with some environments but is otherwise not really needed if you collect data with a single environment at a time (the default).
